### PR TITLE
Add Haskell example

### PR DESCRIPTION
**Pull request by jglukasik**
During Yelp's Hackathon 18 I hacked together an example Haskell program to use the Yelp API, and here it is!

### CODE REVIEW

**Comment by mittonk** [comment]
This looks like a great idea, let me have a look through it.

**Comment by mittonk** [comment]
@tomelm : What do you think of the nested `LICENSE` file?

**Comment by tomelm** [comment]
I'd prefer we remove it. It's less confusing to have all the code samples fall under 1 license then some samples having their own.

**Comment by mittonk** [comment]
@jglukasik : You wrote:
> (and LICENSE for so stack can build)

Can you get the Haskell example running using the main LICENSE (or at least a copy of it)?

I wouldn't use a symlink, given cross-platform concerns (http://stackoverflow.com/questions/5917249/git-symlinks-in-windows).

**Comment by mittonk** [comment]
@jglukasik : Alternatively, if you like your license you can do a dedicated repo, and yelp-api can add a link in README.md.

**Comment by jglukasik** [comment]
The LICENSE file was removed, and now the .cabal file points to the main yelp-api LICENSE file

**Comment by mittonk** [comment]
Sounds good!
:shipit:

**Pull request merged**
