### PR TITLE
Remove Python sample code

### PR DESCRIPTION
**Pull request by tomelm**
We've had the official Python clientlib out for a while now and it's in the readme. Let's remove the sample so people opt for the clientlib.

ref: #81

### CODE REVIEW

**Comment by watterso** [comment]
@tomelm the files changed don't actually mention the remove of the `v2/python` directory, did you do that github just doesn't visualize that correctly?

Otherwise :ship: :shipit:

**Comment by tomelm** [comment]
@watterso correct:

```
yelp-api|remove-python-sample ⇒ ls v2 
csharp      haskell     java        objective-c perl        php         r           rust
```

**Comment by watterso** [comment]
:ship: :shipit: !

**Comment by mittonk** [comment]
:shipit:

**Comment by mittonk** [comment]
Looks like we've got a link from https://www.yelp.com/developers/documentation/v2/examples we should remove.

Rolled back until we update that...

**Pull request merged**
