### PR TITLE
add link to python client library

### PR DESCRIPTION
**Pull request by mathisonian**

### CODE REVIEW

**Comment by mittonk** [comment]
@tomelm just reorganized our "links to other repos" setup in #67 --- let's see if this clientlib has any recent activity.

**Comment by mittonk** [comment]
@mathisonian : Want to update with master, and stick your link in the new "Unofficial" sub-section?

**Comment by mathisonian** [comment]
updated, thanks @mittonk

**Comment by mittonk** [comment]
Thank you @mathisonian !

**Pull request merged**
