### PR TITLE
Python example should quote Unicode paths.

### PR DESCRIPTION
**Pull request by mittonk**
Business IDs can include Unicode; these should be properly encoded as UTF-8 and then URL-encoded when building URLs.
Also display diagnostics as Unicode.  
Refs Issue #33.

### CODE REVIEW

**Comment by mittonk** [comment]
@tomelm , want to check my work?

**Comment by tomelm** [comment]
This looks good to me! :shipit: 

Out of curiosity, @asottile / @bukzor is this somewhere that would be a good use case of [yelp_uri](https://github.com/Yelp/yelp_uri) or [yelp_encodings](https://github.com/Yelp/yelp_encodings)?

**Comment by asottile** [comment]
Yeah this is actually exactly what `yelp_uri`'s `urllib_utf8` module is designed for :)

**Comment by mittonk** [comment]
`yelp_uri` would be an excellent choice here; if this example were larger I'd definitely use it.

For the moment, I'd like to keep dependencies to a minimum.

**Comment by tomelm** [comment]
@mittonk totally cool, I mostly just wanted to know out of curiosity :D. Your point on dependencies is 100% valid!

**Comment by bukzor** [comment]
If this is something meant to be copy-pastad, or meant to show the Right Way to do things, I'd really recommend using yelp_uri.

**Pull request merged**
