### PR TITLE
Add unofficial PHP library

### PR DESCRIPTION
**Pull request by stevenmaguire**
Greetings! I maintain a well tested PHP package that wraps the Yelp API. It has current support of the v2 Fusion API. I would like to add it to the list of packages that are present in this repo. 

Additionally, purely as an FYI, I also maintain the Yelp OAuth2 php package that facilitates authenticated requests to the Yelp API. https://github.com/stevenmaguire/oauth2-yelp

### CODE REVIEW

**Comment by stevenmaguire** [comment]
Any thoughts on this?

**Review by mittonk — APPROVED** [review]
Looks good for Yelp API V2.  (That's not called Fusion.)

We might also want to link to this over at https://github.com/Yelp/yelp-fusion for V3!

**Comment by stevenmaguire** [comment]
Oh, yeah, whoops. v3 is fusion, and that is covered by the package as well. Sorry! Thanks for the merge.

**Comment by stevenmaguire** [comment]
@mittonk PR created in other repo, thanks for the tip. I got the names right this time!

https://github.com/Yelp/yelp-fusion/pull/285

**Pull request merged**
