### PR TITLE
OAuthConsumer update

### PR DESCRIPTION
**Pull request by brennanMKE**
I updated OAuthConsumer to a more current version. Next it would be helpful for the project to include a sample iPhone app with unit tests which work with the current version of Xcode.

### CODE REVIEW

**Comment by mittonk** [comment]
Need to compare against #40  and #45 .

**Comment by tomelm** [comment]
@mittonk I'm inclined to close this given it's 3+ years old at this point and it has conflicts. If you disagree let me know

**Comment by tomelm** [comment]
@mittonk I'm going to close this since it sounds like, at minimum, we'll want either #40 or #45

**Comment by mittonk** [comment]
I concur.

**Pull request closed without merging**
