### PR TITLE
v2 api - browser javascript example

### PR DESCRIPTION
**Pull request by paulirish**
example by prem in https://groups.google.com/forum/#!topic/yelp-developer-support/5bDrWXWJsqY

just making it more findable.

### CODE REVIEW

**Comment by paulirish** [comment]
ping @mittonk

**Comment by tomelm** [comment]
Hey @paulirish! Sorry this didn't get noticed earlier. I'll talk to @mittonk on Tuesday and see about merging this in.

**Comment by paulirish** [comment]
all good. ​

**Comment by mittonk** [comment]
This looks pretty good to me!  Merging.

**Comment by mittonk** [comment]
I'll look into getting a link on
* http://www.yelp.com/developers/documentation/v2/examples

**Comment by paulirish** [comment]
awesome. thanks!!

**Comment by mittonk** [comment]
Hm, looks like this example had been removed in #17 .

Given the security reasons behind that, I think I better roll back @paulirish 's change for now.

**Comment by mittonk** [comment]
Filed #51 for a new JS example that's secure enough for general consumption.

**Comment by paulirish** [comment]
cool! thx.​

i was originally just using JS and porting it into node.
Eventually found the two node-yelp projects which ended up being pretty
useful.

**Pull request merged**
